name: Run serveRest
run-name: ${{ github.actor }} um teste no GitHub Actions 🚀
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build do Gradle e Run Tests
        run: ./gradlew smokeTest
